/*------------------------------------------------------------
File:       02_descriptive.do
Purpose:    Descriptive tables
Inputs:     data/clean/cleaned_dataset.dta
Outputs:    scripts/stata/_outputs/ (balance table)
Run order:  After 01_loadclean.do
------------------------------------------------------------*/
version 19                        // pin Stata semantics
clear all
set more off
set seed 12345                    // determinism for any random ops
set sortseed 12345                // stable sort ties across versions
cap log close
cap log close _all
//-----------------------------------------------------------
*Load data
use "$PROJ/data/clean/cleaned_dataset.dta", clear


*=========
*Counts for Paper
*=========
tab statefip year if mother_elig == 1
*========================================================================
*Table 1: Summary statistics -- mean (SD) by group 2018-2023, weighted)
*Panel A is dependent variables
*Panel B is covariates
*========================================================================
	preserve
		keep if inrange(year, 2018,2023) & mother_elig == 1     // analysis sample: mothers, pre-period
		
		* Panel A: dependent / explanatory (outcome) variables
		local Avars lf_indicator lhours
		local Albls `"  "Labor force participation" "Log hours worked"  "'
		local Atype  pct          raw //assigns each avar a type

		* Panel B: mother-level covariates
		local Bvars age single_mother white black aian asian otherr mixedr hispanic is_citizen in_school diploma associate bachelor high_degree rural nchild hhincome_k
		local Blbls `" "Age" "Single mother" "White, non-Hispanic" "Black, non-Hispanic" "AIAN, non-Hispanic" "Asian/PI, non-Hispanic" "Other race, non-Hispanic" "Two or more races" "Hispanic" "U.S. citizen" "In school" "HS diploma" "Associate degree" "Bachelor's degree" "Graduate degree"  "Nonmetro" "Number of own children" "Household income (thousands)" "'
		local Btype raw pct pct pct pct pct pct pct pct pct pct pct pct pct pct pct raw usd // assigns each bvar a type
			local nA : word count `Avars'
			local nB : word count `Bvars'
			matrix M = J(`=`nA'+`nB'', 4, .) //Counts variables in each panel and builds a matrix with that many rows and 4 columns filled with "."
		* Fill matrix M (cols: 1 T_mean  2 T_sd  3 C_mean  4 C_sd)
		local r = 0                       // matrix row counter (runs across both panels), starts at 0
		foreach v of local Avars {        // Panel A: outcome variables
			local ++r						//next row
			qui summarize `v' [aw=perwt] if Treat == 1   // VT (treated)
			matrix M[`r',1] = r(mean) //stores mean
			matrix M[`r',2] = r(sd) //stores SD
			qui summarize `v' [aw=perwt] if Treat == 0   // control states
			matrix M[`r',3] = r(mean)
			matrix M[`r',4] = r(sd)
		}
		foreach v of local Bvars {        // Panel B: covariates 
			local ++r
			qui summarize `v' [aw=perwt] if Treat == 1
			matrix M[`r',1] = r(mean)
			matrix M[`r',2] = r(sd)
			qui summarize `v' [aw=perwt] if Treat == 0
			matrix M[`r',3] = r(mean)
			matrix M[`r',4] = r(sd)
		}
		* unweighted observation counts per group (%12.0fc = comma-grouped integer)
		count if Treat == 1
		local nTf = string(r(N), "%12.0fc")
		count if Treat == 0
		local nCf = string(r(N), "%12.0fc")

		* echo the same numbers to the results window
		matrix rownames M = `Avars' `Bvars'
		matrix colnames M = T_mean T_sd C_mean C_sd
		matlist M, format(%9.3f) title("Table 1: Mean (SD) by group, pre-period mothers, sample-weighted")

*---------- Write LaTeX ------------ *
*------------------------------------------------------------------------
* Cell formatter
*------------------------------------------------------------------------
cap program drop fmtcell //resets the program
program define fmtcell, rclass
    args v typ
    if "`typ'" == "pct"      return local s = (string(100*`v', "%9.1f")) + "\%"
    else if "`typ'" == "usd" return local s = "\$" + (string(`v', "%9.0fc"))
    else                     return local s = (string(`v', "%9.2f"))
end
*-----------------------------------------------------------------------
		cap mkdir "$PROJ/scripts/stata/_outputs"
		tempname fh //creates a name to more easily reference 
		file open `fh' using "$PROJ/scripts/stata/_outputs/tab_sumstats.tex", write replace text
		file write `fh' "% Auto-generated by 02_descriptive.do -- do not edit by hand." _n
		file write `fh' "{\footnotesize" _n
		file write `fh' "\setlength{\tabcolsep}{4pt}\renewcommand{\arraystretch}{0.9}" _n
		file write `fh' "\begin{tabular}{lcc}" _n
		file write `fh' "\toprule" _n
		file write `fh' " & Treatment & Control \\" _n
		file write `fh' " & mean (sd) & mean (sd) \\" _n
		file write `fh' "\midrule" _n
		* Panel A *
		file write `fh' "\multicolumn{3}{l}{\textit{Dependent / explanatory variables}} \\" _n
		forvalues r = 1/`nA' {
			local lab : word `r' of `Albls'
			local typ : word `r' of `Atype'
			fmtcell M[`r',1] "`typ'" //formats cell according to type
			local mT `r(s)' // treatment mean
			fmtcell M[`r',2] "`typ'"
			local sT `r(s)' // treatment SD
			fmtcell M[`r',3] "`typ'"
			local mC `r(s)' // control mean
			fmtcell M[`r',4] "`typ'"
			local sC `r(s)' // control SD
			file write `fh' "`lab' & `mT' (`sT') & `mC' (`sC') \\" _n //in row writes label and means + SDs 
		}
		file write `fh' "\addlinespace" _n
		* Panel B *
		file write `fh' "\multicolumn{3}{l}{\textit{Covariates}} \\" _n
		forvalues r = 1/`nB' {
			local lab : word `r' of `Blbls'
			local typ : word `r' of `Btype'
			local row = `nA' + `r'                 // Panel B occupies matrix rows nA+1 .. nA+nB
			fmtcell M[`row',1] "`typ'"
			local mT `r(s)'
			fmtcell M[`row',2] "`typ'"
			local sT `r(s)'
			fmtcell M[`row',3] "`typ'"
			local mC `r(s)'
			fmtcell M[`row',4] "`typ'"
			local sC `r(s)'
			file write `fh' "`lab' & `mT' (`sT') & `mC' (`sC') \\" _n
		}
		file write `fh' "\addlinespace" _n
		file write `fh' "Observations & `nTf' & `nCf' \\" _n
		file write `fh' "\bottomrule" _n
		file write `fh' "\end{tabular}" _n
		file write `fh' "}" _n
		file close `fh'
		di as txt "Wrote scripts/stata/_outputs/tab_sumstats.tex"
	restore


*========================================================================
*Table 2: Two-period covariate balance, eligible mothers
* Purpose: justify CONDITIONAL parallel trends for the DR DiD by showing (A) the baseline composition of treated vs. control eligible mothers 
* and (B) whether their covariates were on parallel paths over the pre-period.
* Rule of thumb: |norm./std. diff| > 0.25 = imbalance
*========================================================================

	squi summarize year, meanonly //lets us pull the minimum year, meanonly makes it faster
	local y0 = r(min)      // first pre-year (baseline levels + start of change)
	local y1 = 2023      // last  pre-year (end of change)
	* mother-level covariates (individual versions; pct_* state aggregates excluded)
	local covs age single_mother white black aian asian otherr mixedr hispanic ///
	           is_citizen in_school diploma associate bachelor high_degree rural ///
	           nchild hhincome_k
	local lbls `" "Age" "Single mother" "White, non-Hispanic" "Black, non-Hispanic" "AIAN, non-Hispanic" "Asian/PI, non-Hispanic" "Other race, non-Hispanic" "Two or more races" "Hispanic" "U.S. citizen" "In school" "HS diploma" "Associate degree" "Bachelor's degree" "Graduate degree" "Nonmetro" "Number of own children" "Household income (thousands)" "'
	local nc : word count `covs' //creates a var that is the number of words in this string, each "" is one 'word'

	* ---- Panel A: baseline levels at `y0' -------
	*   cols: 1 Ctrl(unw) 2 VT(unw) 3 ND(unw) 4 Ctrl(wt) 5 VT(wt) 6 ND(wt)
	*   wcol 0 = unweighted cell means, wcol 1 = perwt-weighted cell means.
	matrix A = J(`nc', 6, .)
	forvalues wcol = 0/1 { //loops the next block once with no weights and once with weights
		if `wcol' == 0  local wt ""
		else            local wt "[aw=perwt]"
		local base = 3*`wcol' //allows us to offset to weight columns 
		preserve
			keep if mother_elig == 1 & year == `y0' 
			local r = 0 
	foreach v of local covs {
		local ++r 
		qui summarize `v' `wt' if Treat == 0
		local m0 = r(mean)
		local s0 = r(sd)
		qui summarize `v' `wt' if Treat == 1 
		local m1 = r(mean)
		local s1 = r(sd)
		matrix A[`r',`base'+1] = `m0'
		matrix A[`r', `base' +2] = `m1'
		matrix A[`r', `base'+3] = (`m1'-`m0') / sqrt((`s1'^2 + `s0'^2)/2)
			}
			restore
	}
	matrix rownames A = `covs'
	matrix colnames A = Ctrl_unw VT_unw ND_unw Ctrl_wt VT_wt ND_wt

	* ---- Panel B: (`y1' - `y0') change in state-year cell means -------------------
	*   Same column layout; cols 3/6 = (mean Delta VT - mean Delta control)/SD(Delta control).
	matrix B = J(`nc', 6, .)
	forvalues wcol = 0/1 { 
		if `wcol' == 0  local wt ""
		else            local wt "[aw=perwt]" 
		local base = 3*`wcol' 
		preserve
			keep if mother_elig == 1 & inlist(year, `y0', `y1')
			collapse (mean) `covs' `wt', by(statefip Treat year) //take a weighted avg of each covariate at state level, then group level, then year level 
			reshape wide `covs', i(statefip Treat) j(year) // data starts in different rows by state year, this shifts it so now we have rows by state and columns for each value separated into yearly values for 18 and 23 
			local r = 0
			foreach v of local covs {
				local ++r
				gen double d_`v' = `v'`y1' - `v'`y0' //for all the vars we have made "age2018" and "age2023", this subtracts them
				qui summarize d_`v' if Treat == 0       // across the control states
				local m0 = r(mean)
				local s0 = r(sd)
				qui summarize d_`v' if Treat == 1       // VT specifically
				local m1 = r(mean)
				matrix B[`r', `base'+1] = `m0'
				matrix B[`r', `base'+2] = `m1'
				matrix B[`r', `base'+3] = (`m1'-`m0')/`s0'
			}
		restore
	}
	matrix rownames B = `covs'
	matrix colnames B = Ctrl_unw VT_unw SD_unw Ctrl_wt VT_wt SD_wt

	* ---- echo both panels to the results window ---------------------------------
	matlist A, format(%9.3f) title("Table 2A: Baseline (`y0') levels, eligible mothers; |ND|>0.25 flags imbalance")
	matlist B, format(%9.3f) title("Table 2B: Pre-period change (`y1'-`y0') in cell means; std. by control dispersion")

	* ---- Write LaTeX table -------------------
	cap mkdir "$PROJ/scripts/stata/_outputs"
	tempname fb
	file open `fb' using "$PROJ/scripts/stata/_outputs/tab_balance_2period.tex", write replace text
	file write `fb' "% Auto-generated by 02_descriptive.do -- do not edit by hand." _n
	file write `fb' "{\footnotesize" _n
	file write `fb' "\setlength{\tabcolsep}{3pt}\renewcommand{\arraystretch}{0.75}" _n
	file write `fb' "\begin{tabular}{lcccccc}" _n
	file write `fb' "\toprule" _n
	file write `fb' " & \multicolumn{3}{c}{Unweighted} & \multicolumn{3}{c}{Weighted} \\" _n
	file write `fb' "\cmidrule(lr){2-4}\cmidrule(lr){5-7}" _n
	file write `fb' "Variable & Control & Vermont & Norm. Diff. & Control & Vermont & Norm. Diff. \\" _n
	file write `fb' "\midrule" _n
	file write `fb' "\multicolumn{7}{l}{\textit{Panel A: `y0' baseline levels}} \\" _n
	forvalues r = 1/`nc' {
		local lab : word `r' of `lbls'
		local c1 = string(A[`r',1], "%9.3f")
		local c2 = string(A[`r',2], "%9.3f")
		local c3 = string(A[`r',3], "%9.3f")
		local c4 = string(A[`r',4], "%9.3f")
		local c5 = string(A[`r',5], "%9.3f")
		local c6 = string(A[`r',6], "%9.3f")
		file write `fb' "`lab' & `c1' & `c2' & `c3' & `c4' & `c5' & `c6' \\" _n
	}
	file write `fb' "\addlinespace" _n
	file write `fb' "\multicolumn{7}{l}{\textit{Panel B: `y1'$-$`y0' changes (state-year cell means)}} \\" _n
	file write `fb' "\textit{Variable} & Control & Vermont & Std. Diff. & Control & Vermont & Std. Diff.\\" _n
	forvalues r = 1/`nc' {
		local lab : word `r' of `lbls'
		local c1 = string(B[`r',1], "%9.3f")
		local c2 = string(B[`r',2], "%9.3f")
		local c3 = string(B[`r',3], "%9.3f")
		local c4 = string(B[`r',4], "%9.3f")
		local c5 = string(B[`r',5], "%9.3f")
		local c6 = string(B[`r',6], "%9.3f")
		file write `fb' "`lab' & `c1' & `c2' & `c3' & `c4' & `c5' & `c6' \\" _n
	}
	file write `fb' "\bottomrule" _n
	file write `fb' "\end{tabular}" _n
	file write `fb' "}" _n
	file close `fb'
	di as txt "Wrote scripts/stata/_outputs/tab_balance_2period.tex"

*=================================================================================
*Table 3: Baseline (pre-period) dependent variables, 2023
*  CAVEAT: lhours / wkswork / lincome/ fulltime are conditional on working or
*          earning (>0), so they describe the selected sample of workers/earners.
*=================================================================================
	local outcomes employed lf_indicator fulltime lhours wkswork lincome
	local no : word count `outcomes' //counts the variables in the list
	matrix O = J(`no', 6, .) 
	local r = 0 
	foreach v of local outcomes {
		local ++r 
		* --- unweighted --- * 
		qui summarize `v' if Treat == 0 & year == 2023 & mother_elig == 1 
		local m0 = r(mean)
		local s0 = r(sd)
		qui summarize `v' if Treat == 1 & year == 2023 & mother_elig == 1
		local m1 = r(mean)
		local s1 = r(sd)
		matrix O[`r',1] = `m0' //whichever row we are on, begins populating 
		matrix O[`r',2] = `m1'
		matrix O[`r',3] = (`m1'-`m0') / sqrt((`s1'^2 + `s0'^2)/2) 
		* --- perwt-weighted ---
		qui summarize `v' [aw=perwt] if Treat == 0 & year == 2023 & mother_elig == 1
		local m0 = r(mean)
		local s0 = r(sd)
		qui summarize `v' [aw=perwt] if Treat == 1 & year == 2023 & mother_elig == 1
		local m1 = r(mean)
		local s1 = r(sd)
		matrix O[`r',4] = `m0'
		matrix O[`r',5] = `m1'
		matrix O[`r',6] = (`m1'-`m0') / sqrt((`s1'^2 + `s0'^2)/2)
	}
	matrix rownames O = `outcomes'
	matrix colnames O = Ctrl_unw VT_unw ND_unw Ctrl_wt VT_wt ND_wt
	matlist O, format(%9.3f) title("Table 3: Baseline (2023) dependent variables; pre-treatment comparison")


*============================================================================
*Figure 1: Two-Way Pre-Trends Figure: LFP, Vermont vs. control states
*============================================================================
	preserve
		collapse (mean) lf_indicator [pw=perwt] if mother_elig == 1, by(Treat year)
		rename lf_indicator LFP
		gen VT = cond(Treat == 1, "Vermont", "Control States")
		qui summarize year
		local ymin = r(min)
		local ymax = r(max)

		twoway ///
			  (line    LFP year if Treat == 1, lcolor(red)  lpattern(solid) lwidth(medium)) ///
			  (line    LFP year if Treat == 0, lcolor(blue) lpattern(solid) lwidth(medium)) ///
			  (scatter LFP year if Treat == 1, msymbol(O)  mcolor(red)) ///
			  (scatter LFP year if Treat == 0, msymbol(Oh) mcolor(blue)) , ///
			  legend(order(1 "Vermont" 2 "Control States") pos(6) ring(2) cols(2)) ///
			  xtitle("") ///
			  ytitle("Labor Force Participation", orientation(horizontal)) ///
			  ysize(5) xsize(10) ///
			  xline(2023.5, lpattern(dash) lcolor(gs8)) ///
			  xlabel(`ymin' (1)`ymax', nogrid) ///
			  graphregion(color(white)) ///
			  plotregion(style(none))

		cap mkdir "$PROJ/figures"
		graph export "$PROJ/figures/figure1_stata.pdf", replace
		di as txt "Wrote figures/figure1_stata.pdf"
	restore
*============================================================================
*Figure 2: Two-Way Pre-Trends Figure: Hours Worked, Vermont vs. control states
*============================================================================
	preserve
		collapse (mean) lhours [pw=perwt] if mother_elig == 1, by(Treat year)
		rename lhours hrs_work
		gen VT = cond(Treat == 1, "Vermont", "Control States")
		qui summarize year
		local ymin = r(min)
		local ymax = r(max)

		twoway ///
			  (line    hrs_work year if Treat == 1, lcolor(red)  lpattern(solid) lwidth(medium)) ///
			  (line    hrs_work year if Treat == 0, lcolor(blue) lpattern(solid) lwidth(medium)) ///
			  (scatter hrs_work year if Treat == 1, msymbol(O)  mcolor(red)) ///
			  (scatter hrs_work year if Treat == 0, msymbol(Oh) mcolor(blue)) , ///
			  legend(order(1 "Vermont" 2 "Control States") pos(6) ring(2) cols(2)) ///
			  xtitle("") ///
			  ytitle("Average Weekly Log Hours Worked", orientation(horizontal)) ///
			  ysize(5) xsize(10) ///
			  xline(2023.5, lpattern(dash) lcolor(gs8)) ///
			  xlabel(`ymin' (1)`ymax', nogrid) ///
			  graphregion(color(white)) ///
			  plotregion(style(none))

		cap mkdir "$PROJ/figures"
		graph export "$PROJ/figures/figure2_stata.pdf", replace
		di as txt "Wrote figures/figure2_stata.pdf"
	restore
	
